# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nbr <- function(ii, nRow, nCol, nnr) {
    .Call(`_Gapfill_nbr`, ii, nRow, nCol, nnr)
}

sparse_emp_cov_est <- function(X, nRow, nCol, nnr) {
    .Call(`_Gapfill_sparse_emp_cov_est`, X, nRow, nCol, nnr)
}

sparse_lc_cov_est <- function(X, W, nRow, nCol, nnr) {
    .Call(`_Gapfill_sparse_lc_cov_est`, X, W, nRow, nCol, nnr)
}

mean_est <- function(X, nRow, nCol, W) {
    .Call(`_Gapfill_mean_est`, X, nRow, nCol, W)
}

